# Generated by Django 4.2.5 on 2023-09-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('nurse', 'Nurse'), ('tech', 'Technician')], default='manager', max_length=20),
        ),
    ]
