# Generated by Django 4.2.5 on 2023-09-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_unit_temporary_assigned_resource'),
        ('accounts', '0006_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_unit', to='maintenance.unit'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('nurse', 'Nurse'), ('psw', 'PSW (Personal Support Worker)'), ('hk', 'House Keeping'), ('tech', 'Technician')], default='manager', max_length=20),
        ),
    ]
