# Generated by Django 4.2.5 on 2024-05-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryimage_inventory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='icon',
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_card_icon', to='inventory.inventoryimage'),
        ),
    ]
