# Generated by Django 4.2.5 on 2023-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
