# Generated by Django 4.2.5 on 2023-09-19 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_maintenancerequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
