# Generated by Django 4.2.5 on 2023-09-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_company', to='maintenance.company'),
        ),
    ]
