# Generated by Django 4.2.5 on 2023-09-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancerequest_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='maintenance_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issue', to='maintenance.maintenanceitem'),
        ),
    ]
