# Generated by Django 4.2.5 on 2023-09-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_issue_maintenance_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='maintenance.issue'),
        ),
    ]
