# Generated by Django 4.2.5 on 2023-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenancerequest_issue_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
