# Generated by Django 4.2.5 on 2023-09-20 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0008_maintenancerequest_request_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytechnician',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_company', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='companytechnician',
            name='technian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
