# Generated by Django 4.2.5 on 2023-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_maintenancerequest_problemimage_maintenancedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance-attachments'),
        ),
    ]
