# Generated by Django 4.2.5 on 2023-09-22 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='maintenance.issue'),
        ),
    ]
