# Generated by Django 4.2.5 on 2023-09-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_item_company', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='problemImage',
            field=models.ManyToManyField(blank=True, to='maintenance.image'),
        ),
    ]
