# Generated by Django 4.2.5 on 2023-09-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_companyemployee_delete_companytechnician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='maintenance_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_item', to='maintenance.maintenanceitem'),
        ),
        migrations.DeleteModel(
            name='CompanyEmployee',
        ),
    ]
