# Generated by Django 4.2.5 on 2023-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
