# Generated by Django 4.2.5 on 2023-09-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_company', to='maintenance.company'),
        ),
    ]
