# Generated by Django 4.2.5 on 2023-09-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0020_image_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='temporary_assigned_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
