# Generated by Django 4.2.5 on 2023-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_maintenancerequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumn',
            name='status_description',
            field=models.TextField(default='No Description Provided'),
        ),
    ]
