# Generated by Django 4.2.5 on 2023-10-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_kanbancolumn_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumn',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_column_icon', to='maintenance.image'),
        ),
    ]
