# Generated by Django 4.2.5 on 2023-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_kanbancolumn_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
