# Generated by Django 4.2.5 on 2023-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_maintenancerequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
